- hosts: localhost
  tasks:
      - name: Creates for Nginx Directory
        file: 
          path: "{{ base_path }}" 
          state: directory
          owner: "{{ file_owner }}"
          group: "{{ file_group }}" 
          mode: 0777 
      - name: nginx-conf
        template:
          src: template/nginx.j2
          dest: "{{ base_path }}/{{ user_id }}.conf"
          owner:  "{{ file_owner }}"
          group:  "{{ file_group }}"
          mode: 0777
          force: yes
  vars:
    file_owner: prashant
    file_group: staff
    base_path: /tmp/nginx/site-enabled
  vars_files:
    - env.yaml
