
- name: Creates for Nginx Directory
  file: 
    path: "/mnt/efs/site-enabled" 
    state: directory
    owner: "{{ file_owner }}"
    group: "{{ file_group }}" 
    mode: 0777 
- name: nginx-conf
  template:
    src: template/nginx.j2
    dest: "/mnt/efs/site-enabled/{{ user_id }}.conf"
    owner:  "{{ file_owner }}"
    group:  "{{ file_group }}"
    mode: 0777
    force: yes
